services:
  server:
    container_name: service_app
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - rest-network
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: always
  postgres:
    container_name: service_app_db
    build: ./db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - rest-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/usr/app/data:rw
    restart: always
networks:
  rest-network:
    name: rest-network
    driver: bridge